//! Graph Intermediate Representation (GIR) - Core Data Structures
//!
//! The GIR is the heart of OREO - a graph-native representation where code IS a graph,
//! not text that gets parsed into a graph. Every program is a directed acyclic graph
//! of nodes connected by typed edges.

use std::collections::{HashMap, HashSet};
use std::fmt;
use serde::{Deserialize, Serialize};
use petgraph::graph::{NodeIndex, EdgeIndex};
use petgraph::Direction;

pub mod nodes;
pub mod edges;
pub mod graph;
pub mod types;
pub mod serialization;

pub use nodes::*;
pub use edges::*;
pub use graph::*;
pub use types::*;
pub use serialization::*;

/// Unique identifier for a graph node
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NodeId(pub u64);

/// Unique identifier for a graph edge
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EdgeId(pub u64);

/// Unique identifier for a type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct TypeId(pub u64);

/// Unique identifier for an effect
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct EffectId(pub u64);

/// Port identifier on a node
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PortId {
    pub node_id: NodeId,
    pub index: u32,
    pub direction: PortDirection,
}

/// Direction of a port (input or output)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PortDirection {
    Input,
    Output,
}

/// Source location for debugging and error reporting
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SourceLocation {
    pub file: Option<String>,
    pub line: Option<u32>,
    pub column: Option<u32>,
    pub span: Option<(u32, u32)>, // (start, end) byte offsets
}

impl SourceLocation {
    pub fn unknown() -> Self {
        SourceLocation {
            file: None,
            line: None,
            column: None,
            span: None,
        }
    }
}

impl fmt::Display for SourceLocation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if let Some(file) = &self.file {
            write!(f, "{}", file)?;
            if let Some(line) = self.line {
                write!(f, ":{}", line)?;
                if let Some(col) = self.column {
                    write!(f, ":{}", col)?;
                }
            }
        } else {
            write!(f, "<unknown>")?;
        }
        Ok(())
    }
}

/// Metadata attached to nodes and edges
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct NodeMetadata {
    /// Natural language description that produced this node
    pub nl_description: Option<String>,
    /// Source location in original NL or text
    pub source_location: Option<SourceLocation>,
    /// User-defined annotations
    pub annotations: HashMap<String, serde_json::Value>,
    /// Whether this node was generated by AI
    pub ai_generated: bool,
    /// Confidence score for AI-generated nodes (0.0 - 1.0)
    pub confidence: Option<f32>,
    /// Version/timestamp for incremental compilation
    pub version: u64,
}

/// Global GIR context containing all graphs and type/effect registries
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GirContext {
    /// All graphs in the program (modules, functions, etc.)
    pub graphs: HashMap<GraphId, GirGraph>,
    /// Type registry
    pub type_registry: TypeRegistry,
    /// Effect registry
    pub effect_registry: EffectRegistry,
    /// Next available IDs
    next_node_id: u64,
    next_edge_id: u64,
    next_type_id: u64,
    next_effect_id: u64,
    next_graph_id: u64,
}

/// Unique identifier for a graph
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct GraphId(pub u64);

impl GirContext {
    pub fn new() -> Self {
        GirContext {
            graphs: HashMap::new(),
            type_registry: TypeRegistry::new(),
            effect_registry: EffectRegistry::new(),
            next_node_id: 1,
            next_edge_id: 1,
            next_type_id: 1,
            next_effect_id: 1,
            next_graph_id: 1,
        }
    }

    pub fn create_graph(&mut self, name: String) -> GraphId {
        let id = GraphId(self.next_graph_id);
        self.next_graph_id += 1;
        let graph = GirGraph::new(id, name);
        self.graphs.insert(id, graph);
        id
    }

    pub fn get_graph(&self, id: GraphId) -> Option<&GirGraph> {
        self.graphs.get(&id)
    }

    pub fn get_graph_mut(&mut self, id: GraphId) -> Option<&mut GirGraph> {
        self.graphs.get_mut(&id)
    }

    pub fn next_node_id(&mut self) -> NodeId {
        let id = NodeId(self.next_node_id);
        self.next_node_id += 1;
        id
    }

    pub fn next_edge_id(&mut self) -> EdgeId {
        let id = EdgeId(self.next_edge_id);
        self.next_edge_id += 1;
        id
    }

    pub fn next_type_id(&mut self) -> TypeId {
        let id = TypeId(self.next_type_id);
        self.next_type_id += 1;
        id
    }

    pub fn next_effect_id(&mut self) -> EffectId {
        let id = EffectId(self.next_effect_id);
        self.next_effect_id += 1;
        id
    }
}

impl Default for GirContext {
    fn default() -> Self {
        Self::new()
    }
}

/// A single graph in the GIR (module, function, scope, etc.)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GirGraph {
    pub id: GraphId,
    pub name: String,
    /// Nodes in this graph
    pub nodes: HashMap<NodeId, Box<dyn GirNode>>,
    /// Edges connecting nodes
    pub edges: HashMap<EdgeId, GirEdge>,
    /// Adjacency for fast traversal
    pub adjacency: HashMap<NodeId, Vec<EdgeId>>,
    /// Reverse adjacency
    pub reverse_adjacency: HashMap<NodeId, Vec<EdgeId>>,
    /// Entry points (e.g., main function, module exports)
    pub entry_points: Vec<NodeId>,
    /// Graph-level metadata
    pub metadata: NodeMetadata,
}

/// Trait for all node types in the GIR
pub trait GirNode: fmt::Debug + Send + Sync {
    fn id(&self) -> NodeId;
    fn node_type(&self) -> NodeType;
    fn input_ports(&self) -> &[Port];
    fn output_ports(&self) -> &[Port];
    fn metadata(&self) -> &NodeMetadata;
    fn metadata_mut(&mut self) -> &mut NodeMetadata;
    fn clone_box(&self) -> Box<dyn GirNode>;
    fn as_any(&self) -> &dyn std::any::Any;
    fn as_any_mut(&mut self) -> &mut dyn std::any::Any;
}

/// Discriminant for node type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum NodeType {
    Value,
    Op,
    Control,
    Type,
    Effect,
    Meta,
}

/// A port on a node (input or output)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Port {
    pub id: PortId,
    pub name: String,
    pub port_type: TypeId,
    pub direction: PortDirection,
    pub is_required: bool,
    pub default_value: Option<serde_json::Value>,
}

/// An edge connecting two ports
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GirEdge {
    pub id: EdgeId,
    pub source: PortId,
    pub target: PortId,
    pub edge_type: EdgeType,
    pub metadata: NodeMetadata,
}

/// Type of edge in the graph
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EdgeType {
    Data,
    Control,
    Dependency,
    Composition,
    Annotation,
}

/// Registry for all types in the program
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeRegistry {
    pub types: HashMap<TypeId, TypeInfo>,
    pub name_to_id: HashMap<String, TypeId>,
}

impl TypeRegistry {
    pub fn new() -> Self {
        TypeRegistry {
            types: HashMap::new(),
            name_to_id: HashMap::new(),
        }
    }

    pub fn register(&mut self, name: String, info: TypeInfo) -> TypeId {
        let id = TypeId(self.types.len() as u64 + 1);
        self.name_to_id.insert(name.clone(), id);
        self.types.insert(id, info);
        id
    }

    pub fn get(&self, id: TypeId) -> Option<&TypeInfo> {
        self.types.get(&id)
    }

    pub fn get_by_name(&self, name: &str) -> Option<&TypeInfo> {
        self.name_to_id.get(name).and_then(|id| self.types.get(id))
    }
}

impl Default for TypeRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Information about a type
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeInfo {
    pub id: TypeId,
    pub name: String,
    pub kind: TypeKind,
    pub parameters: Vec<TypeId>,
    pub constraints: Vec<TraitConstraint>,
    pub effects: EffectSet,
}

/// Kind of type
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TypeKind {
    Primitive(PrimitiveType),
    Tuple(Vec<TypeId>),
    Record(Vec<(String, TypeId)>),
    Sum(Vec<(String, TypeId)>), // ADT variants
    Array(TypeId, Option<u64>), // element type, optional size
    Map(TypeId, TypeId),        // key, value
    Option(TypeId),
    Result(TypeId, TypeId),     // Ok, Err
    Function(FunctionType),
    Generic(TypeId),            // Type variable
    Effect(EffectId),
    Unknown,
}

/// Primitive types
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum PrimitiveType {
    Int(u8),      // Int(8), Int(16), Int(32), Int(64), Int(128)
    UInt(u8),     // UInt(8), UInt(16), UInt(32), UInt(64), UInt(128)
    Float(u8),    // Float(16), Float(32), Float(64), Float(80)
    Bool,
    Char,
    String,
    Bytes,
}

/// Function type with parameters, return, and effects
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionType {
    pub params: Vec<(String, TypeId)>, // name, type
    pub return_type: TypeId,
    pub effects: EffectSet,
    pub is_async: bool,
    pub is_const: bool,
}

/// Effect set - a set of effects
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct EffectSet {
    pub effects: HashSet<EffectId>,
}

impl EffectSet {
    pub fn new() -> Self {
        EffectSet { effects: HashSet::new() }
    }

    pub fn add(&mut self, effect: EffectId) {
        self.effects.insert(effect);
    }

    pub fn remove(&mut self, effect: EffectId) {
        self.effects.remove(&effect);
    }

    pub fn contains(&self, effect: EffectId) -> bool {
        self.effects.contains(&effect)
    }

    pub fn union(&self, other: &EffectSet) -> EffectSet {
        let mut result = self.clone();
        result.effects.extend(other.effects.iter().copied());
        result
    }

    pub fn intersects(&self, other: &EffectSet) -> bool {
        self.effects.intersection(&other.effects).next().is_some()
    }

    pub fn is_subset_of(&self, other: &EffectSet) -> bool {
        self.effects.is_subset(&other.effects)
    }

    pub fn is_pure(&self) -> bool {
        self.effects.is_empty()
    }
}

/// Trait constraint for generics
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraitConstraint {
    pub trait_name: String,
    pub type_params: Vec<TypeId>,
}

/// Registry for all effects
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EffectRegistry {
    pub effects: HashMap<EffectId, EffectInfo>,
    pub name_to_id: HashMap<String, EffectId>,
}

impl EffectRegistry {
    pub fn new() -> Self {
        EffectRegistry {
            effects: HashMap::new(),
            name_to_id: HashMap::new(),
        }
    }

    pub fn register(&mut self, name: String, info: EffectInfo) -> EffectId {
        let id = EffectId(self.effects.len() as u64 + 1);
        self.name_to_id.insert(name.clone(), id);
        self.effects.insert(id, info);
        id
    }

    pub fn get(&self, id: EffectId) -> Option<&EffectInfo> {
        self.effects.get(&id)
    }

    pub fn get_by_name(&self, name: &str) -> Option<&EffectInfo> {
        self.name_to_id.get(name).and_then(|id| self.effects.get(id))
    }
}

impl Default for EffectRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Information about an effect
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EffectInfo {
    pub id: EffectId,
    pub name: String,
    pub kind: EffectKind,
    pub parameters: Vec<TypeId>,
    pub description: String,
}

/// Kind of effect
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EffectKind {
    IO,
    State(TypeId),       // State at a location
    Exception(TypeId),   // Exception type
    Async,
    Resource(TypeId),    // Resource type
    Custom(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gir_context_creation() {
        let mut ctx = GirContext::new();
        let graph_id = ctx.create_graph("main".to_string());
        assert_eq!(graph_id, GraphId(1));
        
        let graph = ctx.get_graph(graph_id).unwrap();
        assert_eq!(graph.name, "main");
    }

    #[test]
    fn test_effect_set_operations() {
        let mut set1 = EffectSet::new();
        let mut set2 = EffectSet::new();
        
        let e1 = EffectId(1);
        let e2 = EffectId(2);
        
        set1.add(e1);
        set2.add(e2);
        
        assert!(set1.contains(e1));
        assert!(!set1.contains(e2));
        
        let union = set1.union(&set2);
        assert!(union.contains(e1));
        assert!(union.contains(e2));
        
        assert!(set1.is_subset_of(&union));
        assert!(!set2.is_subset_of(&set1));
    }

    #[test]
    fn test_type_registry() {
        let mut registry = TypeRegistry::new();
        let type_id = registry.register(
            "Int32".to_string(),
            TypeInfo {
                id: TypeId(1),
                name: "Int32".to_string(),
                kind: TypeKind::Primitive(PrimitiveType::Int(32)),
                parameters: vec![],
                constraints: vec![],
                effects: EffectSet::new(),
            }
        );
        
        assert_eq!(type_id, TypeId(1));
        assert!(registry.get_by_name("Int32").is_some());
    }
}